- models/aging_ar_scrubbed/aging_ar_doctor_v2.sql
Fix name reference: `doctor.firstname` , `doctor.lastname`
> Update aging_ar_doctor_v2 name reference

- models/aging_ar_scrubbed/aging_ar_details.sql
> Fix aging_ar_details doctor name

- models/rcm/rcm_all_lineitem_transactions.sql
- models/rcm/rcm_all_lineitems.sql
> removal of nonexistent fields

- models/chronometer_scrubbed/billing_billinglineitem.sql
- models/chronometer_scrubbed/billing_cashpayment.sql
- models/chronometer_scrubbed/billing_cptcode.sql
- models/chronometer_scrubbed/billing_eraobject.sql
- models/chronometer_scrubbed/billing_lineitemtransaction.sql
- models/chronometer_scrubbed/chronometer_appointment.sql
- models/chronometer_scrubbed/chronometer_office.sql
- models/chronometer_scrubbed/chronometer_patient.sql
pointed all models in scubbed folder to the chronometer_scrubbed schema. added two new models to scrub patients and appointments.
{% endif %}
> fixing scrubbed modelling

- models/intermediate/int_lineitems.sql
- models/intermediate/int_lineitems_transactions.sql
- models/marts/daysheet/mrt_daysheet_adjustments.sql
- models/marts/daysheet/mrt_daysheet_credits.sql
- models/marts/daysheet/mrt_daysheet_debits.sql
- models/sources.yml
> Scrubbed working branch

- dbt_project.yml
- models/test/chronometer_scrubbed/billing_billinglineitem.sql
- models/test/chronometer_scrubbed/billing_cashpayment.sql
- models/test/chronometer_scrubbed/billing_lineitemtransaction.sql
- models/test/chronometer_scrubbed/chronometer_appointment.sql
We need to change materilization type to table for sigma to be able to access properly. But in order to keep the size of these clean copies down, we are limiting it to 2023 data for the main transactional tables in use. 
{% endif %}
> changed to default to tables instead views, add date filter

- models/test/chronometer_scrubbed/chronometer_patient.sql
forgot to add middle name initial to patient scrubbed. this missing field is causing intermediate table to fail
{% endif %}
> fix missing field from patients table

- .github/workflows/dbt_ci.yml
- tests/generic/not_empty.sql
- tests/test_patientpayments.sql
Just testing out the workflow, after switching from local `.env` file to Actions Repository Secrets
> Update dbt_ci workflow

- dbt_project.yml
- models/admin/node_storage.sql
- models/admin/table_sizes.sql
We'll want to start using dashboards to track the health of our platform.
To start, I've created a Sigma dashboard built on top of tables that break down the warehouse's disk space utilization, at the level of tables, schemas, and cluster nodes.
N/A
(see screenshot)
N/A
> Create dbt models for Admin tables

- models/intermediate/int_cashpayments.sql
- models/marts/daysheet/mrt_daysheet_cashpayments.sql
Start the PatientPayments model(s) for the DaySheet report.
{% endif %}
> DaySheet patient payments models

- models/marts/aging_ar_scrubbed/mrt_aging_ar_doctor_v2.sql
Fixes 
`column "ca.first_billed_date" must appear in the GROUP BY clause or be used in an aggregate function`
Updates the `GROUP BY` in `mrt_aging_ar_doctor_v2.sql` to include the missing non-aggregate column.
{% endif %}
> AgingAR: Update doctor_v2 model

- models/intermediate/int_cashpayments.sql
- models/marts/daysheet/mrt_daysheet_cashpayments.sql
Fixes an incorrect column reference, and adds a better alias.
> DaySheet patient payments: update bli.code reference

- models/marts/daysheet/mrt_daysheet_cashpayments.sql
> DaySheet patient payments: Update patient + doctor aliases

- .github/scripts/check_downstream_model_diff.py
- .github/workflows/dbt_ci.yml
- dbt_project.yml
- models/intermediate/int_cashpayments.sql
Ticket: [PRA-22](https://drchrono.atlassian.net/browse/PRA-22)
> [PRA-22] Update CI: add dbt run

- .dbt/profiles.yml
- macros/apply_limit_if_test.sql
- macros/doctor_fields.sql
- models/marts/daysheet/mrt_daysheet_adjustments.sql
- models/marts/daysheet/mrt_daysheet_cashpayments.sql
- models/marts/daysheet/mrt_daysheet_credits.sql
- models/marts/daysheet/mrt_daysheet_debits.sql
- models/marts/daysheet/mrt_daysheet_summary.sql
- models/staging/stg_appointments.sql
- models/staging/stg_patients.sql
- Update the `mrt_` model aliases inside `daysheet_summary.sql` 
- Add a new macro `apply_limit_if_test()` that limits views and models to 100 rows, for rapid testing
- Add aliases inside of `doctor_fields.sql` macro
Tested on local and finished building `+mrt_daysheet_summary.sql` in under 2 minutes.
- Updated `WHERE` clauses: 
- `mrt_daysheet_debits` updated `"No Show"` exclusions
- `stg_appointments` exclude `is_demo_data_patient`
> Update: DaySheet summary

- dbt_project.yml
- models/staging/stg_offices.sql
> (testing dbt build) Add whitespace to stg_offices

- models/admin/node_storage.sql
We need better historical records of warehouse metadata.
This PR updates `node_storage.sql` to maintain snapshots of node storage, for the last 7 days.
Also serves as a POC for self-pruning incremental models.
May need to run `dbt build --full-refresh --select node_storage.sql`
> Enable 7-days history for node_storage.sql

- models/marts/daysheet/mrt_daysheet_adjustments.sql
https://docs.getdbt.com/docs/build/incremental-models#configuring-incremental-strategy
> delete+insert strategy for Adjustments

- deployment.yml
Adds a new file `deployment.yml` 
https://fivetran.com/docs/transformations/dbt/troubleshooting/use-deployment-file
> Add deployment.yml for Fivetran transformations

- deployment.yml
> fix cron expression for deployment.yml

- deployment.yml
> reduce daysheet_summary frequency

- dbt_project.yml
- packages.yml
> Remove dbt_package_evaluator

- deployment.yml
- models/marts/daysheet/mrt_daysheet_adjustments.sql
> Misc other updates

- dbt_project.yml
- deployment.yml
- models/marts/daysheet/mrt_daysheet_adjustments.sql
Fixes this dbt warning:
`18:25:21  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.`
> Fix DBT Warning

- deployment.yml
Trying to offset the `node_storage` and `table_sizes` so they don't run at the same time as the marts.
> Update node_storage + table_sizes runtimes

- models/intermediate/int_lineitems.sql
- models/marts/denial_analysis/denials_billed.sql
- models/marts/denial_analysis/denials_unbilled.sql
- models/marts/denial_analysis/mrt_denials.sql
- models/staging/stg_line_items.sql
First pass at data models.
Ticket: [PRA-42](https://drchrono.atlassian.net/browse/PRA-42)
[PRA-42]: https://drchrono.atlassian.net/browse/PRA-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Denial Analysis: V1

- .dbt/profiles.yml
- deployment.yml
- models/marts/daysheet/mrt_daysheet_summary.sql
fixes cases where patient payments with same details are collapsed on accident by UNIONs.
> Daysheet fixes

- .dbt/profiles.yml
- deployment.yml
- models/intermediate/int_lineitems.sql
- models/marts/aging_ar/mrt_aging_ar_details.sql
- models/marts/daysheet/mrt_daysheet_adjustments.sql
- models/marts/daysheet/mrt_daysheet_cashpayments.sql
- models/marts/daysheet/mrt_daysheet_credits.sql
- models/marts/daysheet/mrt_daysheet_debits.sql
- models/marts/daysheet/mrt_daysheet_summary.sql
- models/util/aging_ar/aging_ar_bucket_options.sql
- models/util/aging_ar/aging_ar_date_types.sql
- models/util/aging_ar/aging_ar_group_by_options.sql
- models/util/daysheet/daysheet_date_types.sql
- models/util/daysheet/daysheet_group_by_options.sql
> Merge staging to main branch

- models/marts/daysheet/mrt_daysheet_adjustments.sql
- models/marts/daysheet/mrt_daysheet_cashpayments.sql
- models/marts/daysheet/mrt_daysheet_credits.sql
Ticket: [PRA-32](https://drchrono.atlassian.net/browse/PRA-32)
[PRA-32]: https://drchrono.atlassian.net/browse/PRA-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Changes for PRA-32

- models/intermediate/int_lineitems_transactions.sql
- models/staging/stg_line_item_transactions.sql
Ticket: [PRA-32](https://drchrono.atlassian.net/browse/PRA-32)
[PRA-32]: https://drchrono.atlassian.net/browse/PRA-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Daysheet credits join
